name: Build PHP 8.2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Run Tests
    uses: WebFiori/workflows/.github/workflows/test-php.yaml@main
    with:
      php-version: '8.2'
      phpunit-config: "tests/phpunit10.xml"
    secrets:
      MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
      MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
      MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}

  code-coverage:
    name: Coverage
    needs: test
    uses: WebFiori/workflows/.github/workflows/coverage-codecov.yaml@main
    with:
      php-version: '8.2'
      coverage-file: 'php-8.2-coverage.xml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
